"""
Bibliography (.bbl) file parser for LaTeX papers.

Extracts bibliographic references from compiled .bbl files generated by LaTeX.
"""

import logging
import re
from pathlib import Path
from typing import Dict

from .models import Reference

logger = logging.getLogger(__name__)


def parse_bbl(bbl_path: Path) -> Dict[str, Reference]:
    """
    Parse a .bbl file and extract references.

    Args:
        bbl_path: Path to .bbl file

    Returns:
        Dictionary mapping cite_key to Reference objects

    Raises:
        FileNotFoundError: If .bbl file does not exist
        OSError: If file cannot be read
    """
    # AI NOTE: .bbl files are generated by LaTeX from .bib sources. They
    # contain the formatted references as they appear in the final PDF.
    # This is what we parse, not the raw .bib file.

    bbl_path = Path(bbl_path)

    if not bbl_path.exists():
        raise FileNotFoundError(f".bbl file not found: {bbl_path}")

    logger.info(f"Parsing .bbl file: {bbl_path}")

    with open(bbl_path, "r", encoding="utf-8", errors="replace") as f:
        bbl_content = f.read()

    references: Dict[str, Reference] = {}

    # Find all \bibitem entries
    # Pattern matches \bibitem[...]{cite_key} (AASTeX natbib-style)
    # Handle multiline content in square brackets
    bibitem_pattern = re.compile(r"\\bibitem\[(.*?)\]\{([^}]+)\}", re.DOTALL)

    # Split content by bibitem entries
    bibitem_split = re.split(r"\\bibitem\[", bbl_content)

    for i, entry in enumerate(bibitem_split):
        if i == 0:
            # First split is before any bibitem (preamble)
            continue

        # Extract the full bibitem entry
        # The format is: [author-list]{cite_key}<rest of entry>
        match = re.match(r"(.*?)\]\{([^}]+)\}", entry, re.DOTALL)
        if match:
            cite_key = match.group(2)
            # Get the rest of the entry (after the closing brace)
            rest_of_entry = entry[match.end() :]
            # Extract author list from square brackets
            author_list = match.group(1)
            bibitem_text = author_list + "\n" + rest_of_entry
        else:
            continue

        try:
            ref = _parse_bibitem(cite_key, bibitem_text)
            references[cite_key] = ref
            logger.debug(f"Parsed reference: {cite_key}")
        except Exception as e:
            logger.warning(f"Failed to parse bibitem {cite_key}: {e}")
            # Store raw entry even if parsing fails
            references[cite_key] = Reference(
                cite_key=cite_key,
                authors="",
                title="",
                year="",
                journal=None,
                raw=bibitem_text,
            )

    logger.info(f"Parsed {len(references)} references from {bbl_path}")
    return references


def _parse_bibitem(cite_key: str, bibitem_text: str) -> Reference:
    """
    Parse a single bibitem entry.

    Args:
        cite_key: BibTeX citation key
        bibitem_text: Text content of the bibitem entry

    Returns:
        Reference object with parsed fields
    """
    # AI NOTE: AASTeX natbib-style format typically has authors on the first
    # line followed by year, journal, and title. Pattern may vary between papers.

    authors = ""
    title = ""
    year = ""
    journal = None

    # Remove LaTeX commands like \apj, \mnras, \aap, etc.
    # These expand to journal abbreviations
    journal_commands = r"\\(apj|apjl|apjs|mnras|aap|aaps|pasj|aj|nature|science)"
    bibitem_text = re.sub(journal_commands, "", bibitem_text)

    # Remove \newblock markers (used in some .bbl formats)
    bibitem_text = re.sub(r"\\newblock", "", bibitem_text)

    # Remove \href and \url commands, keeping the text/URL
    bibitem_text = re.sub(r"\\href\{[^}]+\}\{([^}]+)\}", r"\1", bibitem_text)
    bibitem_text = re.sub(r"\\url\{([^}]+)\}", r"\1", bibitem_text)

    # Split into lines and parse
    lines = [line.strip() for line in bibitem_text.split("\n") if line.strip()]

    if not lines:
        return Reference(
            cite_key=cite_key,
            authors=authors,
            title=title,
            year=year,
            journal=journal,
            raw=bibitem_text,
        )

    # First line typically contains authors and year
    first_line = lines[0]

    # Extract year (4 digits, often in parentheses)
    year_match = re.search(r"\((\d{4})\)", first_line)
    if year_match:
        year = year_match.group(1)
    else:
        # Try standalone year pattern
        year_match = re.search(r"\b(\d{4})\b", first_line)
        if year_match:
            year = year_match.group(1)

    # Remove year and parentheses from first line for author extraction
    first_line_clean = re.sub(r"\(\d{4}\)", "", first_line)
    first_line_clean = re.sub(r"\b\d{4}\b", "", first_line_clean)

    # Extract authors (everything before et al., & or specific patterns)
    # Pattern: "Author1, Author2, ... & Author" or "Author1 et al."
    if "et al." in first_line_clean.lower():
        # Use case-insensitive find to locate "et al." position,
        # then slice the original string to preserve capitalization
        idx = first_line_clean.lower().find("et al.")
        authors = first_line_clean[:idx].strip()
    elif "&" in first_line_clean:
        # Split on "&" and take everything before
        authors = first_line_clean.split("&")[0].strip()
    else:
        # Take first line as authors (may include year)
        authors = first_line_clean.strip()

    # Look for journal pattern in remaining lines
    # Common formats: "Journal, Volume, Page" or "\apj Volume, Page"
    journal_pattern = re.compile(
        r"(?:^|\s)([A-Z][A-Za-z&\.\-]+[\s&\.]*[A-Za-z&\.\-]+)\s*,?\s*\d+", re.MULTILINE
    )

    remaining_text = "\n".join(lines[1:])
    journal_match = journal_pattern.search(remaining_text)
    if journal_match:
        journal = journal_match.group(1).strip()

    # Remove journal from remaining text for title extraction
    title_text = remaining_text
    if journal:
        title_text = title_text.replace(journal, "")

    # Remove page numbers (digits, commas)
    title_text = re.sub(r"\b\d+\s*,\s*\d+\b", "", title_text)
    title_text = re.sub(r"\b\d+\b", "", title_text)

    # Remove DOI and arXiv references
    title_text = re.sub(r"doi:.*$", "", title_text, flags=re.IGNORECASE | re.DOTALL)
    title_text = re.sub(r"arxiv:.*$", "", title_text, flags=re.IGNORECASE | re.DOTALL)
    title_text = re.sub(
        r"ascl\.net.*$", "", title_text, flags=re.IGNORECASE | re.DOTALL
    )

    # Clean up title
    title = title_text.strip()
    # Remove trailing punctuation
    title = re.sub(r"[,.\s]+$", "", title)

    return Reference(
        cite_key=cite_key,
        authors=authors,
        title=title,
        year=year,
        journal=journal,
        raw=bibitem_text,
    )
